# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=500)),
                ('softeng', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='omp.Category')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='omp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.ManyToManyField(to='omp.Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('studentAccess', models.BooleanField(default=False)),
                ('supervisorAccess', models.BooleanField(default=False)),
                ('adminAccess', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.User'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='adminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.User'),
        ),
    ]
