# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_project', to='omp.Project'),
        ),
    ]
