# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adminAccess',
            new_name='admin_Access',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='studentAccess',
            new_name='student_Access',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='supervisorAccess',
            new_name='supervisor_Access',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='omp.Category'),
        ),
    ]
