# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0002_auto_20170206_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='assigned',
            field=models.IntegerField(default=0),
        ),
    ]
