# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0004_auto_20161016_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=15),
        ),
    ]
