# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0005_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_Access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_Access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='supervisor_Access',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
