# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0007_auto_20161016_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrator',
            name='adminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.User'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.User'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.User'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
