# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0009_auto_20161024_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='adminID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='supervisorID',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='administrator',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
