# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0011_auto_20161031_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omp.Category'),
        ),
    ]
