# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0012_auto_20161031_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favourites',
            field=models.ManyToManyField(default='None', related_name='favourite_projects', to='omp.Project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_project', to='omp.Project'),
        ),
    ]
