# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0013_auto_20161122_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_projects', to='omp.Project'),
        ),
    ]
