# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0014_auto_20161122_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('project', models.ManyToManyField(to='omp.Project')),
                ('student', models.ManyToManyField(to='omp.Student')),
            ],
        ),
    ]
