# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omp', '0015_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_projects', to='omp.Project'),
        ),
    ]
